name: gozar_vpn
description: Cross-platform VPN client powered by Xray-core with domain restrictions and routing rules.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.0
  http: ^1.2.0
  workmanager: ^0.5.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/xray/geosite.dat
    - assets/xray/geoip.dat
